name: 버-그
description: 으에엨
title: "[Bug 🐛] "
labels: ["Bug 🐛"]
body:
  - type: textarea
    id: to-recreate
    attributes:
      label: 내용
      description: 무엇이, 어째서, 왜?
      placeholder: |
        1.
        2.
        3.
        ...
